version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
        - DATA_SOURCE=192.168.127.65
        - DATA_BASE=Escola
        - PASSWORD_DATABASE=abcd.1234
